### ISSUE TITLE
Error on Quest3 (Android)

### ISSUE THREAD

**Issue by STak4** [kshoji/Unity-MIDI-Plugin-supports#22]
Hi. I tested on Quest3 but not working because of BLE.
It works fine if disable BLEMidiUnityPlugin.

I won't use BLE, but do you plan to resolve the error or add an option to disable BLE?

The error is below.

こんにちは。QuestでMIDIを扱えるプラグインを探していたところ現在も更新されているこちらを試してみることにしました。
エディタ、PCだと正しく動作しますがQuest3だとBLEプラグインがエラーになり全て動作しません。
試しに bleMidiPlugin = null, bool AndroidIsBluetoothEnabled()でfalseを返すようにしたところエラーが消えUSBで正しく動作しました。

現状BLEを使用する予定はないのですがこちらのエラーの改善予定、もしくは `FEATURE_ANDROID_COMPANION_DEVICE`のようにオプション化する予定はありますか？

エラーは下記です。

> 21:37:40.978
Unity
AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Ljp/kshoji/unity/midi/BleMidiUnityPlayerActivity;
21:37:40.978
Unity
java.lang.NoClassDefFoundError: Failed resolution of: Ljp/kshoji/unity/midi/BleMidiUnityPlayerActivity;
21:37:40.978
Unity
at jp.kshoji.unity.midi.BleMidiUnityPlugin.initialize(BleMidiUnityPlugin.java:484)
21:37:40.978
Unity
at jp.kshoji.unity.midi.BleMidiUnityPlugin.initialize(BleMidiUnityPlugin.java:478)
21:37:40.978
Unity
Caused by: java.lang.ClassNotFoundException: jp.kshoji.unity.midi.BleMidiUnityPlayerActivity
21:37:40.978
Unity
... 2 more
21:37:40.978
Unity
at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0
21:37:40.978
Unity
at UnityEngine.AndroidJavaObject._Call (System.IntPtr methodID, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0
21:37:40.978
Unity
at jp.kshoji.unity.midi.MidiManager.AndroidBleMidiPluginInitialize () [0x00000] in <00000000000000000000000000000000>:0
21:37:40.978
Unity
at jp.kshoji.unity.midi.MidiManager.InitializeMidi (System.Action initializeCompletedAction) [0x00000] in <00000000000000000000000000000000>:0
21:37:40.978
Unity
at jp.ksh

**Comment by kshoji** [comment]
I checked the native library included in the latest version (1.4.3), and the BleMidiUnityPlayerActivity class seemed to exist.
Some classes may have been deleted or renamed by proguard.

If you are using proguard, please check if adding the following settings to the `Assets\Plugins\Android\proguard-user.txt` file resolves the issue.

最新版(1.4.3)に同梱されているネイティブライブラリを確認したのですが、aar中にBleMidiUnityPlayerActivity クラスは存在していました。
proguard によりクラスが削除・リネームされているのかもしれません。

もしproguardを使っているのであれば、`Assets\Plugins\Android\proguard-user.txt` ファイルに下記の設定を追加することで解消するかご確認をお願いします。

```proguard-user.txt
# keep everything in this package from being removed or renamed
-keep class jp.kshoji.** { *; }
```

**Comment by kshoji** [comment]
We will consider improving the behavior when an exception occurs from the native library, such as issuing an error log and continuing processing.

ネイティブライブラリでの例外時の挙動については、エラーログを出して処理を継続するなど改善を検討します。
